/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/games/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poll the current round and finalize any action whose end time has passed.
         * @description Wait for activeAction=null before sending the next action. Calls advance the
         *     simulation clock: passive energy drain and time penalties are applied.
         *     A generic success message does not rule out a silent movement/rotation failure.
         */
        get: operations["state"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/current/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Queue one action. Acceptance does not mean the action has finished.
         * @description Move/rotate: ~1s, 1 energy. Wait: ~2s, 1 energy, plus solar charging.
         *     Collect rock/soil: ~2s, 2 energy, on the sample's cell. Analyze: ~3s, 3 energy.
         *     Durations vary ±15%. Movement/rotation may silently fail (6%, 12% on gravel
         *     for movement); verify using GPS/IMU after activeAction becomes null.
         */
        post: operations["act"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/current/beacon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the navigation beacon for the next target, available with any loadout.
         * @description Costs 1 energy in an active round, including ~10% signal dropouts.
         *     Bearing is relative to the rover: positive=right, negative=left, zero=ahead.
         *     Distance is in cells, in a straight line, not a traversable route.
         *     Gaussian noise has standard deviations 8° and 1.5 cells, not hard bounds.
         *     When inactive, all three values are null and no reading energy is charged.
         */
        get: operations["beacon"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/current/sensors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read selected installed sensors. Each requested, installed sensor costs 1 energy.
         * @description Every omitted selection flag defaults to true. For a GPS-only reading set
         *     gps=true AND depthCamera=false, imu=false, sampleDetector=false.
         *     Uninstalled/unselected sensors are omitted. Signal dropout still costs energy.
         *     Calls advance simulation time. Coordinates use a top-left origin, x east, y south.
         */
        get: operations["sensor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/current/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop the current round immediately, cancelling any pending rover action. */
        post: operations["stop_game"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loadout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List equipment, mass and score penalties. Maximum mass is 6 kg. */
        get: operations["loadout"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Identify the player associated with the API key. */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read mission rules, startup information, energy costs, reliability and scoring. */
        get: operations["rules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/submission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Start a round immediately with the submitted equipment.
         * @description Development uses a random map; mission uses the fixed evaluation map.
         *     A random starting position and eastward heading are chosen, but coordinates,
         *     orientation and map are omitted from this response. No waypoint list is supplied.
         *     Replaces an active round, deducting 150 points per remaining target from it.
         */
        put: operations["submission"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Action: {
            action: components["schemas"]["Kind"];
        };
        ApiError: {
            error: string;
        };
        BeaconReading: {
            /**
             * Format: double
             * @description Relative bearing: positive=right, negative=left. Gaussian noise σ=8°;
             *     it can exceed ±180° after noise. Null on dropout or an inactive round.
             */
            bearingDeg: number | null;
            /**
             * Format: double
             * @description Straight-line distance in cells, clamped to >=0. Gaussian noise σ=1.5.
             */
            distance: number | null;
            /**
             * Format: int32
             * @description Next target (1-3), or null when the round is inactive.
             */
            target: number | null;
        };
        CameraCell: {
            kind: null | components["schemas"]["Surface"];
            /** Format: int32 */
            x: number;
            /** Format: int32 */
            y: number;
        };
        /** @enum {string} */
        ControllerMode: "development" | "mission";
        DepthReading: {
            /** @description One cell ahead and three at distance two; absolute grid coordinates. */
            cells: components["schemas"]["CameraCell"][];
            /** Format: int32 */
            cost: number;
            /**
             * Format: double
             * @description Near-cell dropout probability (0.1); far cells have probability 0.2.
             */
            dropout: number;
        };
        /**
         * @description Controller state. Position, orientation and map are obtained through sensors,
         *     not through this response. The browser's additional fields are not part of this contract.
         */
        GameView: {
            activeAction: null | components["schemas"]["Pending"];
            /** Format: int32 */
            analysed: number;
            /** Format: double */
            coveragePercent: number;
            /** Format: int64 */
            elapsedSeconds: number;
            /** Format: int32 */
            energy: number;
            id: string;
            loadout: components["schemas"]["Loadout"];
            /** Format: double */
            loadoutMassKg: number;
            /** Format: int32 */
            maxEnergy: number;
            message: string;
            metrics: components["schemas"]["Metrics"];
            mode: components["schemas"]["Mode"];
            /** Format: int32 */
            rocks: number;
            /** Format: int32 */
            score: number;
            /** Format: int32 */
            soil: number;
            solar: components["schemas"]["SolarState"];
            status: components["schemas"]["Status"];
            /**
             * Format: int32
             * @description Number of targets reached in order (0-3), not the next target's number.
             */
            target: number;
        };
        GpsReading: {
            /** Format: double */
            dropout: number;
            /** Format: int32 */
            x: number;
            /** Format: int32 */
            y: number;
        };
        ImuReading: {
            /**
             * Format: double
             * @description Exact heading: north=0, east=90, south=180, west=270.
             */
            headingDeg: number;
        };
        /** @enum {string} */
        Kind: "move_forward" | "rotate_left" | "rotate_right" | "wait" | "collect_rock" | "collect_soil" | "analyze_sample";
        Loadout: {
            batteryUpgrade: boolean;
            depthCamera: boolean;
            gps: boolean;
            imu: boolean;
            sampleDetector: boolean;
            solarPanel: components["schemas"]["Solar"];
        };
        LoadoutCatalog: {
            components: components["schemas"]["LoadoutComponent"][];
            /** Format: double */
            massBudgetKg: number;
        };
        LoadoutComponent: {
            description: string;
            key: string;
            /** Format: double */
            massKg: number;
            name: string;
            /** Format: int32 */
            points: number;
        };
        Me: {
            email: string;
            playerId: string;
            role: string;
            username: string;
        };
        Metrics: {
            /** Format: int32 */
            distanceTraveled: number;
            /** Format: int32 */
            moves: number;
            /** Format: int32 */
            sensorReads: number;
            /** Format: int32 */
            wallHits: number;
        };
        /** @enum {string} */
        Mode: "development" | "mission" | "testing";
        Pending: {
            /** Format: date-time */
            endsAt: string;
            /** Format: date-time */
            issuedAt: string;
            kind: components["schemas"]["Kind"];
        };
        /** @enum {string} */
        SampleKind: "rock" | "soil";
        SampleReading: {
            /**
             * Format: int32
             * @description 1 or 2 cells ahead. Move onto the sample's cell to collect it.
             */
            distance: number | null;
            kind: null | components["schemas"]["SampleKind"];
        };
        SensorReadings: {
            /** @description Omitted unless requested and installed. */
            depthCamera?: components["schemas"]["DepthReading"];
            gps?: null | components["schemas"]["GpsReading"];
            /** @description Omitted unless requested and installed. */
            imu?: components["schemas"]["ImuReading"];
            /** @description Omitted unless requested and installed. */
            sampleDetector?: components["schemas"]["SampleReading"];
            /** Format: date-time */
            serverTime: string;
        };
        /** @enum {string} */
        Solar: "none" | "compact" | "extended";
        SolarState: {
            blocked: boolean;
            /**
             * Format: int32
             * @description Gross energy added by wait: 8/14 in sunlight, 0 without a panel or in shade.
             */
            gain: number;
            panel: components["schemas"]["Solar"];
        };
        /** @enum {string} */
        Status: "active" | "finished" | "destroyed" | "exhausted" | "superseded" | "aborted";
        Submission: components["schemas"]["Loadout"] & {
            mode: components["schemas"]["ControllerMode"];
        };
        /** @enum {string} */
        Surface: "clear" | "rough" | "shaded" | "blocked";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    state: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Controller state (without map or pose) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameView"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No round has been started */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    act: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "action": "move_forward"
                 *     }
                 */
                "application/json": components["schemas"]["Action"];
            };
        };
        responses: {
            /** @description Action accepted; poll current state until idle */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameView"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No round has been started */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Rover busy or round no longer active */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unknown or missing action (plain-text validation error) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    beacon: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Approximate direction and distance to next target */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "bearingDeg": -33.7,
                     *       "distance": 8.4,
                     *       "target": 1
                     *     }
                     */
                    "application/json": components["schemas"]["BeaconReading"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No round has been started */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    sensor: {
        parameters: {
            query?: {
                depthCamera?: boolean;
                gps?: boolean;
                imu?: boolean;
                sampleDetector?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Requested installed sensors and server time */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "gps": {
                     *         "dropout": 0.2,
                     *         "x": 13,
                     *         "y": 8
                     *       },
                     *       "serverTime": "2026-09-27T12:00:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["SensorReadings"];
                };
            };
            /** @description Malformed query parameters (plain-text validation error) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No round has been started */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    stop_game: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Round stopped (or already inactive) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameView"];
                };
            };
            /** @description Missing or invalid authentication */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No round has been started */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    loadout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public equipment catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "components": [
                     *         {
                     *           "description": "Scan în triunghi de 4 celule în față (1 apropiată + 3 la distanță 2). Clasifică suprafața: liber / pietriș / umbră / blocat.",
                     *           "key": "depthCamera",
                     *           "massKg": 2.4,
                     *           "name": "Cameră de adâncime",
                     *           "points": 120
                     *         },
                     *         {
                     *           "description": "Poziție absolută exactă; pierde semnalul (~20%).",
                     *           "key": "gps",
                     *           "massKg": 0.9,
                     *           "name": "GPS",
                     *           "points": 80
                     *         },
                     *         {
                     *           "description": "Orientare exactă. Verifică direcția după fiecare rotație.",
                     *           "key": "imu",
                     *           "massKg": 0.3,
                     *           "name": "IMU / busolă",
                     *           "points": 45
                     *         },
                     *         {
                     *           "description": "Detectează roci/sol în primele 2 celule din față.",
                     *           "key": "sampleDetector",
                     *           "massKg": 1.1,
                     *           "name": "Detector probe",
                     *           "points": 70
                     *         },
                     *         {
                     *           "description": "+8 energie la așteptare în soare.",
                     *           "key": "solarPanel",
                     *           "massKg": 1.6,
                     *           "name": "Panou solar compact",
                     *           "points": 60
                     *         },
                     *         {
                     *           "description": "+14 energie la așteptare în soare.",
                     *           "key": "solarPanelExtended",
                     *           "massKg": 3.2,
                     *           "name": "Panou solar extins",
                     *           "points": 110
                     *         },
                     *         {
                     *           "description": "Capacitate 280 → 380 energie.",
                     *           "key": "batteryUpgrade",
                     *           "massKg": 2,
                     *           "name": "Baterie extinsă",
                     *           "points": 90
                     *         }
                     *       ],
                     *       "massBudgetKg": 6
                     *     }
                     */
                    "application/json": components["schemas"]["LoadoutCatalog"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Player profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    rules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public machine-readable rules */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "actions": {
                     *         "analyze_sample": {
                     *           "durationSeconds": 3
                     *         },
                     *         "collect_rock": {
                     *           "durationSeconds": 2
                     *         },
                     *         "collect_soil": {
                     *           "durationSeconds": 2
                     *         },
                     *         "move_forward": {
                     *           "durationSeconds": 1
                     *         },
                     *         "rotate_left": {
                     *           "durationSeconds": 1
                     *         },
                     *         "rotate_right": {
                     *           "durationSeconds": 1
                     *         },
                     *         "wait": {
                     *           "durationSeconds": 2
                     *         }
                     *       },
                     *       "actuation": {
                     *         "durationJitter": 0.15,
                     *         "moveFailure": 0.06,
                     *         "moveFailureGravel": 0.12,
                     *         "rotateFailure": 0.06
                     *       },
                     *       "energy": {
                     *         "baseMax": 280,
                     *         "gravelMoveExtra": 1,
                     *         "intervalSeconds": 15,
                     *         "passiveDrain": 1,
                     *         "perAction": {
                     *           "analyze": 3,
                     *           "collect": 2,
                     *           "moveForward": 1,
                     *           "rotate": 1,
                     *           "wait": 1
                     *         },
                     *         "perSensor": {
                     *           "beacon": 1,
                     *           "depthCamera": 1,
                     *           "gps": 1,
                     *           "imu": 1,
                     *           "sampleDetector": 1
                     *         },
                     *         "solarGain": {
                     *           "compact": 8,
                     *           "extended": 14
                     *         },
                     *         "upgradedMax": 380
                     *       },
                     *       "grid": {
                     *         "height": 16,
                     *         "width": 24
                     *       },
                     *       "loadout": {
                     *         "components": [
                     *           {
                     *             "description": "Scan în triunghi de 4 celule în față (1 apropiată + 3 la distanță 2). Clasifică suprafața: liber / pietriș / umbră / blocat.",
                     *             "key": "depthCamera",
                     *             "massKg": 2.4,
                     *             "name": "Cameră de adâncime",
                     *             "points": 120
                     *           },
                     *           {
                     *             "description": "Poziție absolută exactă; pierde semnalul (~20%).",
                     *             "key": "gps",
                     *             "massKg": 0.9,
                     *             "name": "GPS",
                     *             "points": 80
                     *           },
                     *           {
                     *             "description": "Orientare exactă. Verifică direcția după fiecare rotație.",
                     *             "key": "imu",
                     *             "massKg": 0.3,
                     *             "name": "IMU / busolă",
                     *             "points": 45
                     *           },
                     *           {
                     *             "description": "Detectează roci/sol în primele 2 celule din față.",
                     *             "key": "sampleDetector",
                     *             "massKg": 1.1,
                     *             "name": "Detector probe",
                     *             "points": 70
                     *           },
                     *           {
                     *             "description": "+8 energie la așteptare în soare.",
                     *             "key": "solarPanel",
                     *             "massKg": 1.6,
                     *             "name": "Panou solar compact",
                     *             "points": 60
                     *           },
                     *           {
                     *             "description": "+14 energie la așteptare în soare.",
                     *             "key": "solarPanelExtended",
                     *             "massKg": 3.2,
                     *             "name": "Panou solar extins",
                     *             "points": 110
                     *           },
                     *           {
                     *             "description": "Capacitate 280 → 380 energie.",
                     *             "key": "batteryUpgrade",
                     *             "massKg": 2,
                     *             "name": "Baterie extinsă",
                     *             "points": 90
                     *           }
                     *         ],
                     *         "massBudgetKg": 6
                     *       },
                     *       "mission": "Atinge cele trei ținte în ordine. Evită pereții și craterele. Pietrișul costă mai mult și eșuează mai des (12%). Comenzile de deplasare pot eșua tăcut: verifică poziția (GPS) și capul (IMU). Probe de rocă/sol: fiecare zăcământ se epuizează după 1-3 colectări (aleator pe rundă).",
                     *       "points": {
                     *         "analysis": 70,
                     *         "final": 300,
                     *         "rock": 35,
                     *         "soil": 25,
                     *         "target": 250
                     *       },
                     *       "samples": {
                     *         "capacity": "1-3 per tile (random per run)",
                     *         "depletesTo": "floor"
                     *       },
                     *       "sensors": {
                     *         "beacon": {
                     *           "bearing": "relative to rover heading; positive=right, negative=left",
                     *           "bearingNoiseStdDevDeg": 8,
                     *           "cost": 1,
                     *           "distance": "straight-line distance in cells",
                     *           "distanceNoiseStdDevCells": 1.5,
                     *           "dropout": 0.1,
                     *           "noiseDistribution": "gaussian"
                     *         },
                     *         "depthCamera": {
                     *           "cells": 4,
                     *           "classes": [
                     *             "clear",
                     *             "rough",
                     *             "shaded",
                     *             "blocked"
                     *           ],
                     *           "cost": 1,
                     *           "dropout": 0.1,
                     *           "farDropout": 0.2,
                     *           "shape": "triangle"
                     *         },
                     *         "gps": {
                     *           "accuracy": "exact",
                     *           "cost": 1,
                     *           "dropout": 0.2
                     *         },
                     *         "imu": {
                     *           "accuracy": "exact",
                     *           "cost": 1
                     *         },
                     *         "sampleDetector": {
                     *           "cost": 1,
                     *           "misread": 0.1,
                     *           "rangeCells": 2
                     *         }
                     *       },
                     *       "startup": {
                     *         "coordinates": "Origin (0,0) at top-left; x increases east, y increases south. North=0, east=90, south=180, west=270 degrees.",
                     *         "headingDeg": 90,
                     *         "mapProvided": false,
                     *         "navigation": "GPS provides position when installed and receiving a signal; IMU provides heading. The beacon is available with any loadout and points only to the next target.",
                     *         "objective": "Reach targets 1, 2, 3 in order; full-map exploration is not required. Samples are optional bonus points.",
                     *         "position": "random floor cell; coordinates are not included in controller state",
                     *         "targetCoordinatesProvided": false
                     *       },
                     *       "time": {
                     *         "penaltyPerSecond": 1
                     *       }
                     *     }
                     */
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    submission: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "batteryUpgrade": false,
                 *       "depthCamera": true,
                 *       "gps": true,
                 *       "imu": true,
                 *       "mode": "development",
                 *       "sampleDetector": false,
                 *       "solarPanel": "none"
                 *     }
                 */
                "application/json": components["schemas"]["Submission"];
            };
        };
        responses: {
            /** @description New round started */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameView"];
                };
            };
            /** @description Equipment exceeds 6 kg mass budget */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Invalid request fields or enum values (plain-text validation error) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
